# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab1084f1329dd78a7b34f77445335f230a6097aef7798b450882d02aee30c0bd7a26275dc187f90cd4efd83b187a400517ca301923b6638020325f98894294a7

test:
  secret_key_base: 0937291ed4dc7b6f1a6ec3f647101e1637083c1364e45e8b1ae36048caf472ad1b73f01f893ca17b46b8899e93596a42f15382a197db0871aeaad56f01ce8045

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
